M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu22.10.1} date Mo 03 Apr 2023 16:10:47 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-03T16:10:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu22.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X56.02Y-35.45
X61.8Y-35.45
T2
X42.9Y-35.5
X66.9Y-35.5
T0
M30
